// <auto-generated />
using System;
using System.Collections.Generic;
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507180214_RelatedEx")]
    partial class RelatedEx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.BodyPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("BodyParts");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsWeight")
                        .HasColumnType("boolean");

                    b.Property<float?>("BaseWeightBodyRatio")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GifUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<List<string>>("Instructions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Keywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Overview")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<List<Guid>>("RelatedExerciseIds")
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Tips")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<List<string>>("Variations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseBodyPart", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BodyPartId")
                        .HasColumnType("uuid");

                    b.HasKey("ExerciseId", "BodyPartId");

                    b.HasIndex("BodyPartId");

                    b.ToTable("ExerciseBodyParts");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseEquipment", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("ExerciseId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ExerciseEquipments");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseMuscle", b =>
                {
                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MuscleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExerciseId", "MuscleId");

                    b.HasIndex("MuscleId");

                    b.ToTable("ExerciseMuscles");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageRepsPerMinute")
                        .HasColumnType("integer");

                    b.Property<float>("Coefficient")
                        .HasColumnType("real");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("MeasureCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float?>("ReferenceSpeedKmh")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("ExerciseTypes");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Muscle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BodyPartId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BodyPartId");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("Backend.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.AIPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentWeekId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GoalMetadata")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeeksDuration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentWeekId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("AiPlans");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExerciseEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("DistanceMeters")
                        .HasColumnType("real");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("RestAfterCurrentEntrySeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("SetBlockId")
                        .HasColumnType("uuid");

                    b.Property<float?>("SpeedKmh")
                        .HasColumnType("real");

                    b.Property<float?>("WeightKg")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseTypeId");

                    b.HasIndex("SetBlockId");

                    b.ToTable("ExerciseEntries");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExerciseInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float?>("DistanceMeters")
                        .HasColumnType("real");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("ExerciseEntryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<float?>("SpeedKmh")
                        .HasColumnType("real");

                    b.Property<float?>("WeightKg")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseEntryId");

                    b.ToTable("ExerciseIntervals");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExternalTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LoadScore")
                        .HasColumnType("integer");

                    b.Property<string>("PerceivedExertion")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WeekPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId");

                    b.HasIndex("WeekPlanId");

                    b.ToTable("ExternalTrainings");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.PlanTraining", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndPlannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartPlannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrainingNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WeekPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WeekPlanId");

                    b.ToTable("PlanTrainings");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.SetBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RestAfterBlockSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("RestBetweenSetsSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("SetsCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrainingSetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSetId");

                    b.ToTable("SetBlocks");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("PlanTrainingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TrainingSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanTrainingId")
                        .IsUnique();

                    b.HasIndex("TrainingSetId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.TrainingSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyPartFocus")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, float>>("BodyPartPercentages")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<Dictionary<string, float>>("MusclePercentages")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PlanTrainingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SetAccessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrainingType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PlanTrainingId")
                        .IsUnique();

                    b.ToTable("TrainingSets");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.UserWorkloadStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<float>("TotalPercent")
                        .HasColumnType("real");

                    b.Property<Guid>("UserInfoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserInfoId", "Name", "Category")
                        .IsUnique();

                    b.ToTable("UserWorkloadStats");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.WeekPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AIPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("NumberInPlan")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("WeekStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AIPlanId");

                    b.ToTable("WeekPlans");
                });

            modelBuilder.Entity("Backend.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserGoogleToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConnectedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserGoogleTokens");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<decimal>("HeightCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentPlanId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserInfos");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserMetricLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metric")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Metric", "LoggedAt");

                    b.ToTable("UserMetricLogs");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseBodyPart", b =>
                {
                    b.HasOne("Backend.Core.Entities.ExerciseRelated.BodyPart", "BodyPart")
                        .WithMany("ExerciseBodyParts")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Exercise", "Exercise")
                        .WithMany("ExerciseBodyParts")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseEquipment", b =>
                {
                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Equipment", "Equipment")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Exercise", "Exercise")
                        .WithMany("ExerciseEquipments")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseMuscle", b =>
                {
                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Exercise", "Exercise")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Muscle", "Muscle")
                        .WithMany("ExerciseMuscles")
                        .HasForeignKey("MuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Muscle");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.ExerciseType", b =>
                {
                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Exercise", "Exercise")
                        .WithMany("ExerciseTypes")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Muscle", b =>
                {
                    b.HasOne("Backend.Core.Entities.ExerciseRelated.BodyPart", "BodyPart")
                        .WithMany("Muscles")
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BodyPart");
                });

            modelBuilder.Entity("Backend.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.AIPlan", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.WeekPlan", "CurrentWeek")
                        .WithMany()
                        .HasForeignKey("CurrentWeekId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Backend.Core.Entities.UserInfo", "UserInfo")
                        .WithMany("Plans")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWeek");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExerciseEntry", b =>
                {
                    b.HasOne("Backend.Core.Entities.ExerciseRelated.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.ExerciseRelated.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.TrainingRelated.SetBlock", "SetBlock")
                        .WithMany("ExerciseEntries")
                        .HasForeignKey("SetBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ExerciseType");

                    b.Navigation("SetBlock");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExerciseInterval", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.ExerciseEntry", "ExerciseEntry")
                        .WithMany("Intervals")
                        .HasForeignKey("ExerciseEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseEntry");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExternalTraining", b =>
                {
                    b.HasOne("Backend.Core.Entities.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Core.Entities.TrainingRelated.WeekPlan", "WeekPlan")
                        .WithMany("ExternalTrainings")
                        .HasForeignKey("WeekPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UserInfo");

                    b.Navigation("WeekPlan");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.PlanTraining", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.WeekPlan", "WeekPlan")
                        .WithMany("PlanTrainings")
                        .HasForeignKey("WeekPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeekPlan");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.SetBlock", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.TrainingSet", "TrainingSet")
                        .WithMany("SetBlocks")
                        .HasForeignKey("TrainingSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSet");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.TrainingSession", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.PlanTraining", "PlanTraining")
                        .WithOne("TrainingSession")
                        .HasForeignKey("Backend.Core.Entities.TrainingRelated.TrainingSession", "PlanTrainingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Backend.Core.Entities.TrainingRelated.TrainingSet", "TrainingSet")
                        .WithMany()
                        .HasForeignKey("TrainingSetId");

                    b.HasOne("Backend.Core.Entities.UserInfo", "UserInfo")
                        .WithMany("Sessions")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanTraining");

                    b.Navigation("TrainingSet");

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.TrainingSet", b =>
                {
                    b.HasOne("Backend.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Core.Entities.TrainingRelated.PlanTraining", "PlanTraining")
                        .WithOne("TrainingSet")
                        .HasForeignKey("Backend.Core.Entities.TrainingRelated.TrainingSet", "PlanTrainingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CreatedBy");

                    b.Navigation("PlanTraining");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.UserWorkloadStat", b =>
                {
                    b.HasOne("Backend.Core.Entities.UserInfo", "UserInfo")
                        .WithMany("WorkloadStats")
                        .HasForeignKey("UserInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.WeekPlan", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.AIPlan", "AIPlan")
                        .WithMany("WeekPlans")
                        .HasForeignKey("AIPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIPlan");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserGoogleToken", b =>
                {
                    b.HasOne("Backend.Core.Entities.User", "User")
                        .WithOne("GoogleToken")
                        .HasForeignKey("Backend.Core.Entities.UserGoogleToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserInfo", b =>
                {
                    b.HasOne("Backend.Core.Entities.TrainingRelated.AIPlan", "CurrentPlan")
                        .WithMany()
                        .HasForeignKey("CurrentPlanId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Backend.Core.Entities.User", "User")
                        .WithOne("UserInfo")
                        .HasForeignKey("Backend.Core.Entities.UserInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Entities.UserMetricLog", b =>
                {
                    b.HasOne("Backend.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.BodyPart", b =>
                {
                    b.Navigation("ExerciseBodyParts");

                    b.Navigation("Muscles");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Equipment", b =>
                {
                    b.Navigation("ExerciseEquipments");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Exercise", b =>
                {
                    b.Navigation("ExerciseBodyParts");

                    b.Navigation("ExerciseEquipments");

                    b.Navigation("ExerciseMuscles");

                    b.Navigation("ExerciseTypes");
                });

            modelBuilder.Entity("Backend.Core.Entities.ExerciseRelated.Muscle", b =>
                {
                    b.Navigation("ExerciseMuscles");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.AIPlan", b =>
                {
                    b.Navigation("WeekPlans");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.ExerciseEntry", b =>
                {
                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.PlanTraining", b =>
                {
                    b.Navigation("TrainingSession");

                    b.Navigation("TrainingSet")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.SetBlock", b =>
                {
                    b.Navigation("ExerciseEntries");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.TrainingSet", b =>
                {
                    b.Navigation("SetBlocks");
                });

            modelBuilder.Entity("Backend.Core.Entities.TrainingRelated.WeekPlan", b =>
                {
                    b.Navigation("ExternalTrainings");

                    b.Navigation("PlanTrainings");
                });

            modelBuilder.Entity("Backend.Core.Entities.User", b =>
                {
                    b.Navigation("GoogleToken");

                    b.Navigation("UserInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Core.Entities.UserInfo", b =>
                {
                    b.Navigation("Plans");

                    b.Navigation("Sessions");

                    b.Navigation("WorkloadStats");
                });
#pragma warning restore 612, 618
        }
    }
}
